[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Essential for Next.js dynamic routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
